// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc2l6ILU-G-U-Dq7t2VEo65cq-yAXXXw0',
    appId: '1:852473898717:web:9b81b5c0fafcf493115d34',
    messagingSenderId: '852473898717',
    projectId: 'project1127-b8627',
    authDomain: 'project1127-b8627.firebaseapp.com',
    storageBucket: 'project1127-b8627.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL3HEF1WyRtbhmsG6Ic3wsji0PMzzYOKo',
    appId: '1:852473898717:android:668e0dc7b9caf2b0115d34',
    messagingSenderId: '852473898717',
    projectId: 'project1127-b8627',
    storageBucket: 'project1127-b8627.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUxkurxIX_QV6SVtvrI8V1Kkoq4xIMgGc',
    appId: '1:852473898717:ios:ad7b8409bb9c2fae115d34',
    messagingSenderId: '852473898717',
    projectId: 'project1127-b8627',
    storageBucket: 'project1127-b8627.appspot.com',
    androidClientId: '852473898717-lev94pqh8m4hklgt32d3fqfbalcn9vnp.apps.googleusercontent.com',
    iosClientId: '852473898717-gd4i1gfnkm1j393l3m12qqehqh7bhq4p.apps.googleusercontent.com',
    iosBundleId: 'com.sj.snslogin.project1127',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUxkurxIX_QV6SVtvrI8V1Kkoq4xIMgGc',
    appId: '1:852473898717:ios:ad7b8409bb9c2fae115d34',
    messagingSenderId: '852473898717',
    projectId: 'project1127-b8627',
    storageBucket: 'project1127-b8627.appspot.com',
    androidClientId: '852473898717-lev94pqh8m4hklgt32d3fqfbalcn9vnp.apps.googleusercontent.com',
    iosClientId: '852473898717-gd4i1gfnkm1j393l3m12qqehqh7bhq4p.apps.googleusercontent.com',
    iosBundleId: 'com.sj.snslogin.project1127',
  );
}
